### ISSUE TITLE
Move surrogate to different domain

### ISSUE THREAD

**Issue by paked** [hackclub/surrogate#3]
Currently surrogate operates on http://surrogate.hackedu.us (from memory). Most filtering systems (at least in Australia) block by the root domain, meaning that the entire site will get blocked, as opposed to just the `surrogate.` address. 

This would be quite problematic, for `labs` and anything else we decide to put there.

**Comment by MaxWofford** [comment]
Thoughts on the following:
```
carroteats.horse
svg.horse
adjoining-starfish.com
```

**Comment by zachlatta** [comment]
I'm cool with adjoining-starfish.com. Will do this.

**Comment by zachlatta** [comment]
Whoops, didn't mean to comment that.

Here's what I meant to say:

Now that we're using hackclub.com instead of hackedu.us, it's all good if surrogate remains on surrogate.hackedu.us because it's the only thing we're using that domain for.

Going to go ahead and close this issue as a result.
